#!/bin/bash

set -eu

BACKUP_PGP_KEY=${BACKUP_PGP_KEY:-/pubkey.asc}
FILE_NAME="$(basename ${BACKUP_FILE})"
FILE_BASE="${FILE_NAME%%.*}"
FILE_EXT="${FILE_NAME#*.}"
OUTPUT="/scratch/${FILE_BASE}.$(date --iso-8601=minutes --utc).${FILE_EXT}.gpg"

mkdir -p /tmp/gnupg
chmod 700 /tmp/gnupg
gpg --homedir /tmp/gnupg --import ${BACKUP_PGP_KEY}
KEY_ID=`gpg --homedir /tmp/gnupg --batch --with-colons /tmp/gnupg/pubring.gpg | head -n1 | cut -d: -f5`

# encrypt
gpg --homedir /tmp/gnupg --output ${OUTPUT} -z 0 --encrypt --trust-model always --recipient ${KEY_ID} ${BACKUP_FILE}

# upload encrypted data
gsutil cp ${OUTPUT} ${BACKUP_BUCKET}

# clean up
rm ${OUTPUT}
